% [ranked_all_Chromosomes_of_all_Iterations all_Chromosomes_of_all_Iterations Bests_of_all_Iterations Global_Best] = Genetic_Algorithm_Manager (     initial_Population, ...                   % A Maxtrix or '' :  Each Column has the results of a Test for All Variables      
%                                                                                                                                                     ...                                      % for ex. :     input_Data = [ Cement       :  1  2  3  4  5 ;
%                                                                                                                                                     ...                                      %                              Lime_Powder  :  6  7  8  9  10;
%                                                                                                                                                     ...                                      %                              Stone_Powder :  11 12 13 14 15;
%                                                                                                                                                     ...                                      %                              ...          :       ...
%                                                                                                                                                     ...                                      %                            ]
%                                                                                                                                                     ...
%                                                                                                                                                     initial_Costs, ...                       % A Vertical Vector or ''
%                                                                                                                                                     ...
%                                                                                                                                                     initial_Parameters, ...                  % Vertical Structure or '' : any Essential parameter for problem (such as u for Cost function)
%                                                                                                                                                     ...
%                                                                                                                                                     number_of_Vars, ...                      % Number of Decision Variables
%                                                                                                                                                     var_Min_Vector, ...                      % Horizontal Vector or '' : Minimum Value of Vars
%                                                                                                                                                     var_Max_Vector, ...                      % Horizontal Vector or '' : Maximum Value of Vars
%                                                                                                                                                     ...
%                                                                                                                                                     draw_the_Convergence_Fig, ...            % 0 or 1 : Draws COnvergence Procedure
%                                                                                                                                                     draw_the_Seperated_Histogram_Figs, ...   % 0 or 1 : Draws Seperated Histogram Figures        
%                                                                                                                                                     draw_the_Integrated_Histogram_Fig, ...   % 0 or 1 : Draws Integrated Histogram Figure       
%                                                                                                                                                     column_Names, ...                        % Column Names for Histogram
%                                                                                                                                                     ...
%                                                                                                                                                     maximum_Iteration, ...
%                                                                                                                                                     population_Size, ...
%                                                                                                                                                     p_CrossOver, ...
%                                                                                                                                                     p_Mutation, ...
%                                                                                                                                                     deviation,...
%                                                                                                                                                     ...
%                                                                                                                                                     the_Num_of_Pops_for_Demonstration, ...   % The Number of populations for Demonstration
%                                                                                                                                                     ...
%                                                                                                                                                     ranking_Policy )                         % 'Descend' or 'Ascend'   : for 'Descend' the 'Global Best' 'increases'
%                                                                                                                                                                                                          %             : for 'Ascend'  the 'Global Best' 'descreases'
%                                                                             
%                                                                             


clc
close all;

tic
[ranked_all_Chromosomes_of_all_Iterations all_Chromosomes_of_all_Iterations Bests_of_all_Iterations Global_Best] = Genetic_Algorithm_Manager (      [], ...                                  % A Maxtrix or '' :  Each Column has the results of a Test for All Variables      
                                                                                                                                                    ...                                      % for ex. :     input_Data = [ Cement       :  1  2  3  4  5 ;
                                                                                                                                                    ...                                      %                              Lime_Powder  :  6  7  8  9  10;
                                                                                                                                                    ...                                      %                              Stone_Powder :  11 12 13 14 15;
                                                                                                                                                    ...                                      %                              ...          :       ...
                                                                                                                                                    ...                                      %                            ]
                                                                                                                                                    ...
                                                                                                                                                    [], ...                                  % A Vertical Vector or ''
                                                                                                                                                    ...
                                                                                                                                                    [ .5  9 ], ...                           % Vertical Structure or '' : any Essential parameter for problem (such as [ epsilon power_of_Row ] for Cost function)
                                                                                                                                                    ...
                                                                                                                                                    7, ...                                 % Number of Decision Variables
                                                                                                                                                    zeros ( 1, 7 ), ...       % Horizontal Vector or '' : Minimum Value of Vars
                                                                                                                                                    100 * ones ( 1, 7 ), ...       % Horizontal Vector or '' : Maximum Value of Vars
                                                                                                                                                    ...
                                                                                                                                                    1, ...                                   % 0 or 1 : Draws COnvergence Procedure
                                                                                                                                                    0, ...                                   % 0 or 1 : Draws Seperated Histogram Figures        
                                                                                                                                                    0, ...                                   % 0 or 1 : Draws Integrated Histogram Figure       
                                                                                                                                                    [], ...                                  % Column Names for Histogram
                                                                                                                                                    ...
                                                                                                                                                    100, ...
                                                                                                                                                    60, ...
                                                                                                                                                    .8, ...
                                                                                                                                                    .1, ...
                                                                                                                                                    10,...
                                                                                                                                                    ...
                                                                                                                                                    .5, ...                             % Baest Value that is Assigned to 'CodeRate' : No Limitation
                                                                                                                                                    .0004, ...                             % 0 <= codeRate_Deviation <= codeRate_Best_Value
                                                                                                                                                    ...
                                                                                                                                                    100, ...                               % The Number of populations for Demonstration
                                                                                                                                                    ...
                                                                                                                                                    'Ascend' )                             % 'Descend' or 'Ascend'   : for 'Descend' the 'Global Best' 'increases'
end_Time = toc;                                                                                                                                                                                                         %             : for 'Ascend'  the 'Global Best' 'descreases'
fprintf ( 'The Total Simulation Time : %d (Seconds) && %d (Minutes) && %d (Hours)', end_Time, end_Time/60, end_Time/3600);

                                                                                         